#pragma once

#include "ninho/simulation/content.hpp"
#include "ninho/simulation/playthrough.hpp"
#include "ninho/simulation/session.hpp"

#include <array>
#include <cstdint>
#include <cstddef>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace ninho::simulation::test {

inline constexpr std::size_t frozen_playthrough_fixture_max_bytes =
    16U * 1024U * 1024U;
inline constexpr std::size_t frozen_playthrough_fixture_max_shots = 4U;
inline constexpr std::size_t frozen_playthrough_fixture_max_blob_bytes =
    4U * 1024U * 1024U;

struct FrozenLegacyQuantizedLaunch {
    std::array<std::int64_t, 3> origin_mm{};
    std::array<std::int64_t, 3> normalized_direction_1e4{};
    std::uint64_t speed_centimeters_per_second{};

    bool operator==(const FrozenLegacyQuantizedLaunch&) const = default;
};

// Named source parameters for the schema-v1 ring launcher.  Product-v2
// gesture routes compare against the canonical AimState generated by this
// public legacy API; they do not claim command-stream identity across schemas.
struct LegacyAimSeed {
    double theta_deg{};
    double phase_deg{};
    double speed_m_s{};

    bool operator==(const LegacyAimSeed&) const = default;
};

struct FrozenPlaythroughExpected {
    Outcome outcome{Outcome::None};
    std::uint64_t score{};
    std::uint32_t stars{};
    std::uint32_t birds_remaining{};
    bool objectives_complete{};
    std::vector<std::uint8_t> ordered_events_v3;
    std::vector<std::uint8_t> canonical_state_v3;
    std::uint64_t canonical_state_v3_fnv1a64{};
    std::vector<std::uint8_t> canonical_playthrough_v5;
    std::uint64_t canonical_playthrough_v5_fnv1a64{};

    bool operator==(const FrozenPlaythroughExpected&) const = default;
};

struct FrozenPlaythroughFixture {
    std::uint32_t schema_version{};
    std::string route_id;
    PlaythroughRouteDefinition route;
    std::vector<std::optional<FrozenLegacyQuantizedLaunch>> legacy_quantized_launches;
    FrozenPlaythroughExpected expected;

    bool operator==(const FrozenPlaythroughFixture&) const = default;
};

struct FrozenReplayedShot {
    std::uint64_t shot_id{};
    BirdArchetypeId bird_archetype_id{};
    AbilityId ability_id{};
    EntityId primary_projectile_id{};
    TickIndex launch_tick{};
    ninho::physics::Vec3 locked_camera_right{};
    std::optional<FrozenLegacyQuantizedLaunch> quantized_launch;
    std::optional<TickIndex> ability_started_tick;
    bool activation_consumed{};

    bool operator==(const FrozenReplayedShot&) const = default;
};

struct FrozenPlaythroughReplay {
    std::vector<FrozenReplayedShot> shots;
    FrozenPlaythroughExpected actual;

    bool operator==(const FrozenPlaythroughReplay&) const = default;
};

// Parses the closed JSON envelope and verifies blob framing, hashes and route
// binding. Semantic validity of the canonical state belongs to real replay.
[[nodiscard]] ContentResult<FrozenPlaythroughFixture>
parse_frozen_playthrough_fixture_envelope(std::string_view document) noexcept;

[[nodiscard]] std::span<const LegacyAimSeed>
canonical_orbital_legacy_aim_seeds(std::string_view route_id) noexcept;

[[nodiscard]] AimState legacy_ring_aim(LegacyAimSeed seed) noexcept;

// Cross-version launch equivalence uses exact canonical integer units:
// origin at 1 mm, a double-normalized direction rounded component-wise at
// 1e-4, and speed at 0.01 m/s. std::llround supplies ties-away-from-zero.
[[nodiscard]] ContentResult<FrozenLegacyQuantizedLaunch>
canonical_legacy_launch_units(ninho::physics::Vec3 origin_m,
    ninho::physics::Vec3 direction, double speed_m_s) noexcept;

[[nodiscard]] ContentResult<FrozenPlaythroughReplay>
replay_frozen_playthrough(const FrozenPlaythroughFixture& fixture) noexcept;

}
